server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/identity_service}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:root}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey:  "7/m4QxJPPP5R9nLP2O2Q9mSn8hIMmx+G2ytP4DM+lTibMUaKw5FPo0kclAa2AVt4"
  valid-duration: 3600 # in second
  refreshable-duration: 3600 # in seconds
